# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46479005f6658614b7c6113b3bd8a48cfaa1a21f2015d850dd9410e3498bf00a9c9ff544ceb93a5faf8b459e92df8248f9a149fea6a144e80062caeb1535a081

test:
  secret_key_base: 20bbd38201a98a64b7d84535a4259ac2968e2116dd64dab5ca8f993e59bbec1f0dc0498c57c951b201425373ef9573c0270bce0c48d71f0ddd0dd1f899272364

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
